INSERT INTO state VALUES(1,'AA','Armed Forces Americas (except Canada)');
INSERT INTO state VALUES(2,'AE','Armed Forces Africa, Canada, Europe, Middle East');
INSERT INTO state VALUES(3,'AK','Alaska');
INSERT INTO state VALUES(4,'AL','Alabama');
INSERT INTO state VALUES(5,'AP','Armed Forces Pacific');
INSERT INTO state VALUES(6,'AR','Arkansas');
INSERT INTO state VALUES(7,'AS','American Samoa');
INSERT INTO state VALUES(8,'AZ','Arizona');
INSERT INTO state VALUES(9,'CA','California');
INSERT INTO state VALUES(10,'CO','Colorado');
INSERT INTO state VALUES(11,'CT','Connecticut');
INSERT INTO state VALUES(12,'DC','District Of Columbia');
INSERT INTO state VALUES(13,'DE','Delaware');
INSERT INTO state VALUES(14,'FL','Florida');
INSERT INTO state VALUES(15,'FM','Federated States Of Micronesia');
INSERT INTO state VALUES(16,'GA','Georgia');
INSERT INTO state VALUES(17,'GU','Guam');
INSERT INTO state VALUES(18,'HI','Hawaii');
INSERT INTO state VALUES(19,'IA','Iowa');
INSERT INTO state VALUES(20,'ID','Idaho');
INSERT INTO state VALUES(21,'IL','Illinois');
INSERT INTO state VALUES(22,'IN','Indiana');
INSERT INTO state VALUES(23,'KS','Kansas');
INSERT INTO state VALUES(24,'KY','Kentucky');
INSERT INTO state VALUES(25,'LA','Louisiana');
INSERT INTO state VALUES(26,'MA','Massachusetts');
INSERT INTO state VALUES(27,'MD','Maryland');
INSERT INTO state VALUES(28,'ME','Maine');
INSERT INTO state VALUES(29,'MH','Marshall Islands');
INSERT INTO state VALUES(30,'MI','Michigan');
INSERT INTO state VALUES(31,'MN','Minnesota');
INSERT INTO state VALUES(32,'MO','Missouri');
INSERT INTO state VALUES(33,'MP','Northern Mariana Islands');
INSERT INTO state VALUES(34,'MS','Mississippi');
INSERT INTO state VALUES(35,'MT','Montana');
INSERT INTO state VALUES(36,'NC','North Carolina');
INSERT INTO state VALUES(37,'ND','North Dakota');
INSERT INTO state VALUES(38,'NE','Nebraska');
INSERT INTO state VALUES(39,'NH','New Hampshire');
INSERT INTO state VALUES(40,'NJ','New Jersey');
INSERT INTO state VALUES(41,'NM','New Mexico');
INSERT INTO state VALUES(42,'NV','Nevada');
INSERT INTO state VALUES(43,'NY','New York');
INSERT INTO state VALUES(44,'OH','Ohio');
INSERT INTO state VALUES(45,'OK','Oklahoma');
INSERT INTO state VALUES(46,'OR','Oregon');
INSERT INTO state VALUES(47,'PA','Pennsylvania');
INSERT INTO state VALUES(48,'PR','Puerto Rico');
INSERT INTO state VALUES(49,'PW','Palau');
INSERT INTO state VALUES(50,'RI','Rhode Island');
INSERT INTO state VALUES(51,'SC','South Carolina');
INSERT INTO state VALUES(52,'SD','South Dakota');
INSERT INTO state VALUES(53,'TN','Tennessee');
INSERT INTO state VALUES(54,'TX','Texas');
INSERT INTO state VALUES(55,'UT','Utah');
INSERT INTO state VALUES(56,'VA','Virginia');
INSERT INTO state VALUES(57,'VI','Virgin Islands');
INSERT INTO state VALUES(58,'VT','Vermont');
INSERT INTO state VALUES(59,'WA','Washington');
INSERT INTO state VALUES(60,'WI','Wisconsin');
INSERT INTO state VALUES(61,'WV','West Virginia');
INSERT INTO state VALUES(62,'WY','Wyoming');
